# Generated by Django 4.2.5 on 2024-02-24 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='The number must be at least 10 digit long'), django.core.validators.RegexValidator('^9\\d{9}$', message='The number must be start with 9 and 10 dight long')]),
        ),
    ]
